apiVersion: v2
name: vote-app
description: A Helm chart for vote-application
version: 0.1.0
appVersion: 1.0.0
dependencies:
  - name: redis
    version: 17.16.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enable
  - name: postgresql-ha
    version: 11.9.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql-ha.enable